{% set name = "dacite" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/konradhalas/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 791ac3da85a040684a96df59e2320dc7b3cac000ff536e3f4b00fb3b67520b86

build:
  number: 0
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install .  --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - dataclasses # [py<37]

test:
  imports:
    - dacite
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/konradhalas/dacite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    This module simplifies creation of data classes
    (PEP 557) from dictionaries.
  summary: Simple creation of data classes from dictionaries.
  dev_url: https://pypi.org/project/dacite/
  doc_url: https://github.com/konradhalas/dacite/blob/master/README.md
extra:
  recipe-maintainers:
    - mands
