{% set name = "dacite" %}
{% set version = "1.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/konradhalas/{{ name }}/archive/refs/tags/v{{ version }}-fix.tar.gz
  sha256: 67cb6c3af1303cf765fd0f07251ad4c5148127d84142e974f36bad7330e3cd34

build:
  number: 0
  script: {{ PYTHON }} -m pip install .  --no-deps --no-build-isolation -vv
  skip: true # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - dataclasses # [py<37]

test:
  source_files:
    - tests
  imports:
    - dacite
  commands:
    - pip check
    - python -m pytest -v tests
  requires:
    - pip
    - pytest >=5
    - pytest-benchmark

about:
  home: https://github.com/konradhalas/dacite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    This module simplifies creation of data classes
    (PEP 557) from dictionaries.
  summary: Simple creation of data classes from dictionaries.
  dev_url: https://github.com/konradhalas/dacite
  doc_url: https://github.com/konradhalas/dacite/blob/master/README.md

extra:
  recipe-maintainers:
    - mands
